### PR TITLE
Add explicit roles for Private Transactions system

### PR DESCRIPTION
**Pull request by grbIzl**

### CODE REVIEW

**Comment by Tbaut** [comment]
Is there a way to specify these account roles? It's not clear to me if anything should be done on top, or if the goal of this PR is simply to describe the read/write rights of each role?

**Comment by grbIzl** [comment]
@Tbaut The goal was just to explicitly describe these roles as multiple questions appear about them. They implicitly described in the whole document, so @bjornwgnr suggested to summarize it into one text.

**Comment by Tbaut** [comment]
I made some changes to make things as simple as possible (because they are simple)! What do you think?

**Comment by grbIzl** [comment]
@Tbaut Thanks for the changes!

**Pull request merged**
