### PR TITLE
fix extrinsics redirect link

### PR DESCRIPTION
**Pull request by FilipLaurentiu**
[clabot:check]

### CODE REVIEW

**Comment by joshua-mir** [comment]
Hey @FilipLaurentiu this link points to the correct page on wiki.parity.io - where this repo deploys to.

**Comment by FilipLaurentiu** [comment]
image
I get a 404

**Comment by joshua-mir** [comment]
You may notice that all links are 404s *on github*
on wiki.parity.io, after the page is built, they point to the correct page 😅

**Comment by FilipLaurentiu** [comment]
Ok then, sry for that

**Pull request closed without merging**
