### PR TITLE
Polkadot update with GitHub repo link

### PR DESCRIPTION
**Pull request by Tbaut**

### CODE REVIEW

**Comment by Tbaut** [comment]
>Actually, let's not move this away from the wiki. Couldn't we instead maintain this here?

@keorn was more for having it in one place. It costs a copy/paste to the maintainer for now, but won't it be outdated soon again?

>Also, please mark external links in the sidebar somehow.

Logged it here : https://github.com/paritytech/wiki/issues/97

**Comment by 5chdn** [comment]
But this PR moved it away from the one place. :stuck_out_tongue:

**Comment by Tbaut** [comment]
If there should be only one place, then it should be in Polkadot repo IMO as it's where it will most likely be updated.

**Comment by 5chdn** [comment]
No, because repository-wikis are unmaintainable. We moved the Core and Ethereum docs here, why making something else for Polkadot?

**Comment by keorn** [comment]
I maintain the other repo, if you prefer copy pasteing to yours or removing then I am all for it. Just nice not to have old links around.

**Comment by 5chdn** [comment]
:white_flag:

**Pull request merged**
