### PR TITLE
Small wiki updates

### PR DESCRIPTION
**Pull request by Tbaut**
- Remove multi-sig wallet creation from wiki
- Add wallet watch
- Update to 5,000 block time for snapshot updates
- Update token register fee

### CODE REVIEW

**Comment by Tbaut** [comment]
It was confirmed by Felix (don't know his nickname on github) I'll ask him to comment here

**Comment by 5chdn** [comment]
@fevo1971 :)

**Comment by fevo1971** [comment]
Just confirming that the default period between snapshots at the moment is 5000 blocks
(instead of occurring once every 10000 blocks, as stated in the command-line help).

```
parity@kovan-bootnode-0:~$ grep 'Taking snapshot starting at block' parity.log | tail -n5
2018-03-20 14:37:32 UTC Taking snapshot starting at block 6470000
2018-03-20 21:17:00 UTC Taking snapshot starting at block 6475000
2018-03-21 03:49:20 UTC Taking snapshot starting at block 6480000
2018-03-21 09:42:16 UTC Taking snapshot starting at block 6485000
2018-03-21 15:26:40 UTC Taking snapshot starting at block 6490000
```

**Comment by 5chdn** [comment]
Thanks

**Pull request merged**
