### PR TITLE
Reduce the bandwidth tips

### PR DESCRIPTION
**Pull request by jamesray1**

### CODE REVIEW

**Comment by 5chdn** [comment]
Thanks, can you move it to the bottom of the page?

**Comment by jamesray1** [comment]
Done!

**Comment by jamesray1** [comment]
@jsveto I don't know. I have a 64 bit system and it works fine with Ubuntu 17.10.

**Comment by jsveto** [comment]
I recompiled from sources and got it working on 64bit. trickle seems to work i confirmed with:
trickle -d 100 -u 100 wget <some file>. Download speed was aprox. 100Kb/s as expected.

However after running parity under trickle. Bandwidth limiting does not work. Upload was again capped and my internet connection painfully slow. If i shutdown parity, upload/download speed stabilised at few kb/s.

I tried both trickle (to limit bandwidth of single application) and trickled to limit global bandwidth. Nothing seems to work if parity is running.

**Comment by jsveto** [comment]
1.) Start parity as different user. for this example i will use user: test_user

2. mark packets matching uid with iptables
iptables -A OUTPUT -m owner --uid-owner test_user -j MARK --set-mark 6

3.) use tc to limit bandwidth of marked packets
tc qdisk add dev enp7s0 root handle 1: htb
tc class add dev enp7s0 parent 1: classid 1:1 htb rate 500kbit burst 1000kbit

Using this setup, parity upload is limited with 500kbit with occasional bursts. I can still use rest of the bandwidth when using other users.

**Comment by jamesray1** [comment]
Gee, that's complicated! Parity is running now without trickle, while I use the internet, and there has been no noticeable lags. http://www.speedtest.net/result/7117076762. But it has been slow at other times. There is nobody else home at the moment.

**Comment by jamesray1** [comment]
However, I suspect that the reason that Parity is not slowing internet use is because it's slowly increasing above block 4900000, and is probably downloading less and doing more computation.

**Pull request merged**
