### PR TITLE
[WIP] Add sidebar navigation dropdown on hover

### PR DESCRIPTION
**Pull request by iamonuwa**
Fixes https://github.com/paritytech/parity/issues/8923

@Tbaut please comment

### CODE REVIEW

**Comment by Tbaut** [comment]
Thanks for the PR.
As I could test, the menu only hides the "level 3" menu items, I would like the level 2 to be also wrapped (marked in red):
image

Also there is no indication that a menu is a drop-down (red arrow):
image

All in all, everything is already pictured and explained in the issue paritytech/parity#8923:
image

**Comment by iamonuwa** [comment]
@Tbaut thank you for your review. I'll make changes

**Comment by Tbaut** [comment]
BTW the expand should probably be on click to be user-friendly on mobile.
I can modify the wiki to make sure that the titles aren't linking to any content. This way, we could click on a menu title, expand it, and then click on a link. See what I mean?

**Comment by Tbaut** [comment]
@iamonuwa FYI I made a PR https://github.com/paritytech/wiki/pull/186 to remove all links from menu  titles so that the drop-down menus can be clicked without redirection. This is much better for mobile.

**Comment by iamonuwa** [comment]
@Tbaut understood

**Comment by Tbaut** [comment]
Any news on this @iamonuwa?

**Comment by iamonuwa** [comment]
@Tbaut I've tried add javascript but the _Sidebar.md doesn't fit in. Any suggestions?

**Comment by Tbaut** [comment]
What do you mean it doesn't fit?

**Comment by iamonuwa** [comment]
It will only toggle if the selected li is clicked on.

**Comment by Tbaut** [comment]
Yeah toggle the menu on click is what we need. I ran your branch and the expanding is still on mouse hover (instead of click), and there is still no indication that the menu is a drop-down (as explained here https://github.com/paritytech/wiki/pull/184#issuecomment-403403514).

**Comment by Tbaut** [comment]
The drop-down on click is now working well, but the list and their icons is not working as expected. The list-style is sometimes not present, or removed, and does not fit with what was originally asked:

Opening a menu for the first time, all the li have the same icon (we should not have the same icon for drop down and links):
image


Opening a submenu, the original list style is removed
image


This is how I asked originally (note the difference also with an open sub-menu and a closed one):
image

**Comment by iamonuwa** [comment]
Am still working on the icons

**Comment by Tbaut** [comment]
This PR is now not needed anymore as the needed changes were made in https://github.com/paritytech/wiki/pull/205

**Pull request closed without merging**
