### PR TITLE
Update link to non deprecated contracts

### PR DESCRIPTION
**Pull request by Tbaut**

### CODE REVIEW

**Comment by Tbaut** [comment]
@andresilva can you have a look please?

**Comment by andresilva** [comment]
I'm not sure whether we should update the link to that repo. I think the idea for that repo was to have just the validator set contract that is going to be used in the Kovan network, and not necessarily contain all the different `ValidatorSet` implementations we have available.

**Comment by Tbaut** [comment]
Thanks for the comment, I wouldn't like to link deprecated repo, any better suggestion?

**Comment by Tbaut** [comment]
Sounds like a good alternative.

**Comment by andresilva** [comment]
Sorry for being late but LGTM 👍 I will start working on the validator set contracts soon so if necessary we can revisit this afterwards.

**Pull request merged**
